/**
 * Broker registry — single source of truth for /brokers/[slug] SEO pages.
 *
 * Source-of-truth notes:
 *  - For brokers where the exact in-app export path is volatile or
 *    where I don't have first-hand recent confirmation, `exportPath` uses
 *    a generic placeholder rather than fabricated specifics. Update with
 *    accurate path when verified against the broker's current UI.
 *  - `relatedPatterns` slugs MUST exist in lib/seo/patternRegistry.ts.
 *  - `slug` MUST be lowercase + hyphenated (matches /brokers/[slug] route).
 */

export interface BrokerInfo {
  slug: string
  name: string
  fullName: string
  market: 'india' | 'us' | 'crypto' | 'forex' | 'global'
  asset_classes: ('equity' | 'options' | 'futures' | 'forex' | 'crypto')[]
  description: string
  exportFormats: string[]
  exportPath: string
  fileNamePattern: string
  columnsAnalyzed: string[]
  relatedPatterns: string[]
  homepageUrl: string
  foundedYear: number
  headquarters: string
}

const PLACEHOLDER_PATH = 'Reports → Trade History (verify in your broker\'s documentation)'

const STANDARD_COLUMNS = ['symbol', 'side', 'qty', 'price', 'date', 'time']

export const BROKERS: BrokerInfo[] = [
  // ─────────────────────────────────────────────────────────────────
  // INDIAN BROKERS (7)
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'zerodha',
    name: 'Zerodha',
    fullName: 'Zerodha Broking Ltd',
    market: 'india',
    asset_classes: ['equity', 'options', 'futures'],
    description: 'India\'s largest discount broker, serving over 13 million active clients on the Kite trading platform. Best known for flat-fee F&O brokerage and the Console reporting portal.',
    exportFormats: ['CSV', 'XLSX'],
    exportPath: 'Console → Reports → Tradebook → Select date range → Download CSV',
    fileNamePattern: 'tradebook-EQUITY-XXXXXX.csv',
    columnsAnalyzed: ['symbol', 'isin', 'trade_date', 'exchange', 'segment', 'series', 'trade_type', 'auction', 'quantity', 'price', 'trade_id', 'order_id', 'order_execution_time'],
    relatedPatterns: ['revenge-trade', 'fomo-re-entry', 'overtrading', 'averaging-down'],
    homepageUrl: 'https://zerodha.com',
    foundedYear: 2010,
    headquarters: 'Bangalore, India',
  },
  {
    slug: 'upstox',
    name: 'Upstox',
    fullName: 'RKSV Securities India Pvt Ltd',
    market: 'india',
    asset_classes: ['equity', 'options', 'futures'],
    description: 'Tiger Global-backed Indian discount broker with strong mobile-first experience. Reports are exported from the Upstox web platform under My Account.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: 'Web → My Account → Reports → Trade Report → Download',
    fileNamePattern: 'trade-report-XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['revenge-trade', 'fomo-re-entry', 'overtrading'],
    homepageUrl: 'https://upstox.com',
    foundedYear: 2009,
    headquarters: 'Mumbai, India',
  },
  {
    slug: 'angel-one',
    name: 'Angel One',
    fullName: 'Angel One Ltd',
    market: 'india',
    asset_classes: ['equity', 'options', 'futures'],
    description: 'One of India\'s oldest full-service brokers turned digital, with a large F&O retail base. Tradebook export is available from the back-office reports portal.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'AngelOne-Tradebook-XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['revenge-trade', 'overtrading', 'panic-exit'],
    homepageUrl: 'https://www.angelone.in',
    foundedYear: 1996,
    headquarters: 'Mumbai, India',
  },
  {
    slug: 'groww',
    name: 'Groww',
    fullName: 'Groww (Nextbillion Technology Pvt Ltd)',
    market: 'india',
    asset_classes: ['equity', 'options', 'futures'],
    description: 'Mobile-first Indian discount broker focused on simple onboarding and a younger retail audience. Reports are available from the in-app Reports section.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'groww-tradebook-XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['fomo-re-entry', 'overtrading', 'late-entry'],
    homepageUrl: 'https://groww.in',
    foundedYear: 2016,
    headquarters: 'Bangalore, India',
  },
  {
    slug: 'fyers',
    name: 'FYERS',
    fullName: 'FYERS Securities Pvt Ltd',
    market: 'india',
    asset_classes: ['equity', 'options', 'futures'],
    description: 'Indian discount broker popular with active intraday and options traders for its API access and TradingView-integrated charts.',
    exportFormats: ['CSV', 'XLSX'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'FYERS_TradeBook_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['revenge-trade', 'overtrading', 'panic-exit', 'averaging-down'],
    homepageUrl: 'https://fyers.in',
    foundedYear: 2015,
    headquarters: 'Bangalore, India',
  },
  {
    slug: 'icici-direct',
    name: 'ICICI Direct',
    fullName: 'ICICI Securities Ltd',
    market: 'india',
    asset_classes: ['equity', 'options', 'futures'],
    description: 'Bank-backed Indian full-service broker with a long history. Tradebook is exported from the ICICI Direct web portal under Trade History.',
    exportFormats: ['CSV', 'XLSX'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'ICICIDirect_Trades_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['hope-and-hold', 'late-entry', 'averaging-down'],
    homepageUrl: 'https://www.icicidirect.com',
    foundedYear: 2000,
    headquarters: 'Mumbai, India',
  },
  {
    slug: 'kotak-securities',
    name: 'Kotak Securities',
    fullName: 'Kotak Securities Ltd',
    market: 'india',
    asset_classes: ['equity', 'options', 'futures'],
    description: 'Bank-affiliated Indian broker with a full-service legacy and a discount-tier offering. Tradebook export is from the trade reports portal.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'Kotak_Trades_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['hope-and-hold', 'averaging-down', 'late-entry'],
    homepageUrl: 'https://www.kotaksecurities.com',
    foundedYear: 1994,
    headquarters: 'Mumbai, India',
  },

  // ─────────────────────────────────────────────────────────────────
  // US BROKERS (7)
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'robinhood',
    name: 'Robinhood',
    fullName: 'Robinhood Markets Inc',
    market: 'us',
    asset_classes: ['equity', 'options', 'crypto'],
    description: 'Commission-free US broker that popularised retail options trading. Trade history is exported via Account → Statements & History.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: 'Account → Statements & History → Account Statements / Tax Documents',
    fileNamePattern: 'Robinhood_Account_Statement_XXXXXX.csv',
    columnsAnalyzed: ['Activity Date', 'Process Date', 'Settle Date', 'Instrument', 'Description', 'Trans Code', 'Quantity', 'Price', 'Amount'],
    relatedPatterns: ['fomo-re-entry', 'revenge-trade', 'chasing-momentum', 'overtrading'],
    homepageUrl: 'https://robinhood.com',
    foundedYear: 2013,
    headquarters: 'Menlo Park, USA',
  },
  {
    slug: 'webull',
    name: 'Webull',
    fullName: 'Webull Financial LLC',
    market: 'us',
    asset_classes: ['equity', 'options', 'crypto'],
    description: 'Zero-commission US broker known for Level 2 quotes and active-trader UI. Trade history is exported from the Account section.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: 'Account → Documents → Trade Confirmations / Account Statements',
    fileNamePattern: 'Webull_Trades_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['fomo-re-entry', 'revenge-trade', 'chasing-momentum'],
    homepageUrl: 'https://www.webull.com',
    foundedYear: 2017,
    headquarters: 'New York, USA',
  },
  {
    slug: 'tastytrade',
    name: 'tastytrade',
    fullName: 'tastytrade Inc',
    market: 'us',
    asset_classes: ['equity', 'options', 'futures'],
    description: 'US broker built specifically for options and futures traders, with deep volatility and probability tooling. Trade history is exported from the History tab.',
    exportFormats: ['CSV'],
    exportPath: 'Activity → History → Filter by date → Export to CSV',
    fileNamePattern: 'tastytrade_history_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['premature-exit', 'late-entry', 'position-sizing-error'],
    homepageUrl: 'https://tastytrade.com',
    foundedYear: 2017,
    headquarters: 'Chicago, USA',
  },
  {
    slug: 'charles-schwab',
    name: 'Charles Schwab',
    fullName: 'The Charles Schwab Corporation',
    market: 'us',
    asset_classes: ['equity', 'options', 'futures'],
    description: 'US discount broker giant. Trade history is exported from the History & Statements section of schwab.com.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: 'Accounts → History & Statements → Transactions → Export',
    fileNamePattern: 'Schwab_Transactions_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['hope-and-hold', 'late-entry', 'sunk-cost-fallacy'],
    homepageUrl: 'https://www.schwab.com',
    foundedYear: 1971,
    headquarters: 'Westlake, Texas, USA',
  },
  {
    slug: 'fidelity',
    name: 'Fidelity',
    fullName: 'Fidelity Investments',
    market: 'us',
    asset_classes: ['equity', 'options', 'futures'],
    description: 'Large US full-service broker and asset manager. Trade history is exported from the Activity & Orders portal.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: 'Accounts & Trade → Activity & Orders → History → Download',
    fileNamePattern: 'Fidelity_Activity_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['hope-and-hold', 'sunk-cost-fallacy'],
    homepageUrl: 'https://www.fidelity.com',
    foundedYear: 1946,
    headquarters: 'Boston, USA',
  },
  {
    slug: 'etrade',
    name: 'E*TRADE',
    fullName: 'E*TRADE from Morgan Stanley',
    market: 'us',
    asset_classes: ['equity', 'options', 'futures'],
    description: 'US online broker now part of Morgan Stanley. Trade history is exported from the Accounts → Transactions section.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: 'Accounts → Transactions → Filter date range → Download',
    fileNamePattern: 'ETRADE_Transactions_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['hope-and-hold', 'late-entry'],
    homepageUrl: 'https://us.etrade.com',
    foundedYear: 1982,
    headquarters: 'New York, USA',
  },
  {
    slug: 'interactive-brokers',
    name: 'Interactive Brokers',
    fullName: 'Interactive Brokers LLC',
    market: 'global',
    asset_classes: ['equity', 'options', 'futures', 'forex'],
    description: 'Professional-grade global broker covering 150+ markets. Trade history is exported from the Performance & Reports portal as a Flex Query or Activity Statement.',
    exportFormats: ['CSV', 'XLSX', 'PDF'],
    exportPath: 'Performance & Reports → Statements → Activity → Custom date range → Download CSV',
    fileNamePattern: 'IBKR_Activity_Statement_XXXXXX.csv',
    columnsAnalyzed: ['Symbol', 'DateTime', 'Quantity', 'TradePrice', 'IBCommission', 'NetCash', 'Buy/Sell', 'AssetClass', 'Currency'],
    relatedPatterns: ['premature-exit', 'late-entry', 'position-sizing-error'],
    homepageUrl: 'https://www.interactivebrokers.com',
    foundedYear: 1978,
    headquarters: 'Greenwich, Connecticut, USA',
  },

  // ─────────────────────────────────────────────────────────────────
  // GLOBAL BROKERS (6)
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'saxo-bank',
    name: 'Saxo Bank',
    fullName: 'Saxo Bank A/S',
    market: 'global',
    asset_classes: ['equity', 'options', 'futures', 'forex'],
    description: 'Danish multi-asset broker covering 70+ exchanges. Reports are exported from the SaxoTraderGO web platform under Account → Reports.',
    exportFormats: ['CSV', 'XLSX', 'PDF'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'SaxoBank_Trades_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['late-entry', 'position-sizing-error', 'overtrading'],
    homepageUrl: 'https://www.home.saxo',
    foundedYear: 1992,
    headquarters: 'Copenhagen, Denmark',
  },
  {
    slug: 'etoro',
    name: 'eToro',
    fullName: 'eToro Group Ltd',
    market: 'global',
    asset_classes: ['equity', 'forex', 'crypto'],
    description: 'Israel-headquartered social trading platform popular for copy-trading and crypto. Trade history is exported from the Portfolio history page.',
    exportFormats: ['CSV', 'XLSX'],
    exportPath: 'Portfolio → History → Account Statement → Generate report',
    fileNamePattern: 'eToro_Account_Statement_XXXXXX.xlsx',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['fomo-re-entry', 'herd-behavior', 'chasing-momentum'],
    homepageUrl: 'https://www.etoro.com',
    foundedYear: 2007,
    headquarters: 'Tel Aviv, Israel',
  },
  {
    slug: 'ig-markets',
    name: 'IG Markets',
    fullName: 'IG Group Holdings plc',
    market: 'global',
    asset_classes: ['equity', 'forex', 'futures'],
    description: 'UK-based CFD and spread-betting broker with global reach. Reports are exported from the My Account section.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'IG_Statement_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['position-sizing-error', 'overtrading', 'panic-exit'],
    homepageUrl: 'https://www.ig.com',
    foundedYear: 1974,
    headquarters: 'London, UK',
  },
  {
    slug: 'plus500',
    name: 'Plus500',
    fullName: 'Plus500 Ltd',
    market: 'global',
    asset_classes: ['equity', 'forex', 'crypto'],
    description: 'Israeli/UK CFD broker known for its retail-focused web and mobile platform. Reports are exported from the Account Statement page.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'Plus500_Statement_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['overtrading', 'fomo-re-entry'],
    homepageUrl: 'https://www.plus500.com',
    foundedYear: 2008,
    headquarters: 'Haifa, Israel',
  },
  {
    slug: 'capital-com',
    name: 'Capital.com',
    fullName: 'Capital Com SV Investments Ltd',
    market: 'global',
    asset_classes: ['equity', 'forex', 'crypto'],
    description: 'Cyprus-based CFD broker with AI-driven trade analysis features. Trade history is exported from the Reports section of the platform.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'CapitalCom_Trades_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['overtrading', 'position-sizing-error'],
    homepageUrl: 'https://capital.com',
    foundedYear: 2016,
    headquarters: 'Limassol, Cyprus',
  },
  {
    slug: 'xtb',
    name: 'XTB',
    fullName: 'X-Trade Brokers DM SA',
    market: 'global',
    asset_classes: ['equity', 'forex', 'futures'],
    description: 'Polish forex and CFD broker with European listings. Reports are exported from the xStation account history.',
    exportFormats: ['CSV', 'XLSX'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'XTB_Account_History_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['position-sizing-error', 'overtrading'],
    homepageUrl: 'https://www.xtb.com',
    foundedYear: 2002,
    headquarters: 'Warsaw, Poland',
  },

  // ─────────────────────────────────────────────────────────────────
  // FOREX (4)
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'oanda',
    name: 'OANDA',
    fullName: 'OANDA Corporation',
    market: 'forex',
    asset_classes: ['forex'],
    description: 'US/UK forex and CFD broker known for its API and FX data services. Trade history is exported from the Reports section of fxTrade.',
    exportFormats: ['CSV', 'XLSX'],
    exportPath: 'fxTrade → My Account → Reports → Transaction History → Export CSV',
    fileNamePattern: 'OANDA_Transactions_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['position-sizing-error', 'overtrading', 'late-entry'],
    homepageUrl: 'https://www.oanda.com',
    foundedYear: 1996,
    headquarters: 'New York, USA',
  },
  {
    slug: 'metatrader-4',
    name: 'MetaTrader 4',
    fullName: 'MetaTrader 4 (MetaQuotes Software)',
    market: 'forex',
    asset_classes: ['forex', 'futures'],
    description: 'Industry-standard forex trading platform used by many brokers. Trade history is exported from the Account History tab as a CSV or HTM report.',
    exportFormats: ['CSV', 'HTM'],
    exportPath: 'Terminal → Account History tab → Right-click → Save As Report',
    fileNamePattern: 'StatementXXXXXX.htm',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['position-sizing-error', 'overtrading'],
    homepageUrl: 'https://www.metaquotes.net/en/metatrader4',
    foundedYear: 2005,
    headquarters: 'Limassol, Cyprus',
  },
  {
    slug: 'metatrader-5',
    name: 'MetaTrader 5',
    fullName: 'MetaTrader 5 (MetaQuotes Software)',
    market: 'forex',
    asset_classes: ['forex', 'futures', 'equity'],
    description: 'MT4\'s successor with multi-asset support. Trade history is exported from the History tab via right-click → Save Report.',
    exportFormats: ['CSV', 'HTML', 'XLSX'],
    exportPath: 'Toolbox → History tab → Right-click → Report → Open XML / Save As',
    fileNamePattern: 'ReportHistory-XXXXXX.html',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['position-sizing-error', 'overtrading'],
    homepageUrl: 'https://www.metaquotes.net/en/metatrader5',
    foundedYear: 2010,
    headquarters: 'Limassol, Cyprus',
  },
  {
    slug: 'forex-com',
    name: 'FOREX.com',
    fullName: 'GAIN Capital Holdings (StoneX Group)',
    market: 'forex',
    asset_classes: ['forex'],
    description: 'US-regulated forex broker, part of StoneX. Reports are exported from the Account Statements section of the trader portal.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'FOREXcom_Statement_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['position-sizing-error', 'overtrading'],
    homepageUrl: 'https://www.forex.com',
    foundedYear: 2001,
    headquarters: 'New Jersey, USA',
  },

  // ─────────────────────────────────────────────────────────────────
  // CRYPTO (8)
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'binance',
    name: 'Binance',
    fullName: 'Binance Holdings Ltd',
    market: 'crypto',
    asset_classes: ['crypto', 'futures'],
    description: 'World\'s largest crypto exchange by spot and derivatives volume. Trade history is exported from the Wallet → Transaction History page.',
    exportFormats: ['CSV', 'XLSX'],
    exportPath: 'Wallet → Transaction History → Export → Trade History → Generate CSV',
    fileNamePattern: 'binance-trade-history-XXXXXX.csv',
    columnsAnalyzed: ['Date(UTC)', 'Pair', 'Side', 'Price', 'Executed', 'Amount', 'Fee'],
    relatedPatterns: ['fomo-re-entry', 'chasing-momentum', 'revenge-trade', 'overtrading'],
    homepageUrl: 'https://www.binance.com',
    foundedYear: 2017,
    headquarters: 'Cayman Islands',
  },
  {
    slug: 'coinbase',
    name: 'Coinbase',
    fullName: 'Coinbase Global Inc',
    market: 'crypto',
    asset_classes: ['crypto'],
    description: 'US-listed crypto exchange with strong regulatory compliance. Trade history is exported from the Reports section as CSV.',
    exportFormats: ['CSV', 'PDF'],
    exportPath: 'Profile → Reports → Generate Report → Transaction History → CSV',
    fileNamePattern: 'Coinbase-TransactionsHistoryReport-XXXXXX.csv',
    columnsAnalyzed: ['Timestamp', 'Transaction Type', 'Asset', 'Quantity Transacted', 'Spot Price Currency', 'Spot Price at Transaction', 'Subtotal', 'Total', 'Fees'],
    relatedPatterns: ['fomo-re-entry', 'chasing-momentum'],
    homepageUrl: 'https://www.coinbase.com',
    foundedYear: 2012,
    headquarters: 'San Francisco, USA',
  },
  {
    slug: 'kraken',
    name: 'Kraken',
    fullName: 'Payward Inc',
    market: 'crypto',
    asset_classes: ['crypto', 'futures'],
    description: 'US-based crypto exchange with deep fiat liquidity and a margin/futures arm. Trade history is exported from the History page.',
    exportFormats: ['CSV', 'XLSX'],
    exportPath: 'History → Export → Trades → Select date range → Submit',
    fileNamePattern: 'kraken_trades_XXXXXX.csv',
    columnsAnalyzed: ['txid', 'ordertxid', 'pair', 'time', 'type', 'ordertype', 'price', 'cost', 'fee', 'vol'],
    relatedPatterns: ['fomo-re-entry', 'chasing-momentum'],
    homepageUrl: 'https://www.kraken.com',
    foundedYear: 2011,
    headquarters: 'San Francisco, USA',
  },
  {
    slug: 'bybit',
    name: 'Bybit',
    fullName: 'Bybit Fintech Limited',
    market: 'crypto',
    asset_classes: ['crypto', 'futures'],
    description: 'Crypto derivatives-focused exchange offering perpetual swaps, options, and spot. Trade history is exported from the Asset → Transaction History page.',
    exportFormats: ['CSV', 'XLSX'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'Bybit_Order_Trade_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['position-sizing-error', 'fomo-re-entry', 'chasing-momentum', 'revenge-trade'],
    homepageUrl: 'https://www.bybit.com',
    foundedYear: 2018,
    headquarters: 'Dubai, UAE',
  },
  {
    slug: 'okx',
    name: 'OKX',
    fullName: 'OKX (formerly OKEx)',
    market: 'crypto',
    asset_classes: ['crypto', 'futures'],
    description: 'Top-5 crypto derivatives exchange with strong perpetuals and options markets. Trade history is exported from the Asset → Order Center → History page.',
    exportFormats: ['CSV', 'XLSX'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'OKX_Trade_History_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['position-sizing-error', 'fomo-re-entry', 'chasing-momentum'],
    homepageUrl: 'https://www.okx.com',
    foundedYear: 2017,
    headquarters: 'Seychelles',
  },
  {
    slug: 'bitget',
    name: 'Bitget',
    fullName: 'Bitget Limited',
    market: 'crypto',
    asset_classes: ['crypto', 'futures'],
    description: 'Crypto derivatives exchange known for copy-trading. Trade history is exported from the Asset section of the platform.',
    exportFormats: ['CSV'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'Bitget_Trades_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['herd-behavior', 'fomo-re-entry', 'position-sizing-error'],
    homepageUrl: 'https://www.bitget.com',
    foundedYear: 2018,
    headquarters: 'Singapore',
  },
  {
    slug: 'bitfinex',
    name: 'Bitfinex',
    fullName: 'iFinex Inc',
    market: 'crypto',
    asset_classes: ['crypto', 'futures'],
    description: 'Long-standing crypto exchange popular with high-volume traders. Trade history is exported from Reports → Trades.',
    exportFormats: ['CSV'],
    exportPath: PLACEHOLDER_PATH,
    fileNamePattern: 'Bitfinex_Trades_XXXXXX.csv',
    columnsAnalyzed: STANDARD_COLUMNS,
    relatedPatterns: ['fomo-re-entry', 'position-sizing-error'],
    homepageUrl: 'https://www.bitfinex.com',
    foundedYear: 2012,
    headquarters: 'Hong Kong',
  },
  {
    slug: 'kucoin',
    name: 'KuCoin',
    fullName: 'KuCoin',
    market: 'crypto',
    asset_classes: ['crypto', 'futures'],
    description: 'Wide-altcoin-listing crypto exchange. Trade history is exported from the Orders → Trade History page.',
    exportFormats: ['CSV', 'XLSX'],
    exportPath: 'Orders → Trade History → Export → Filter date range → Download CSV',
    fileNamePattern: 'kucoin_trade_history_XXXXXX.csv',
    columnsAnalyzed: ['UID', 'Account Type', 'Order ID', 'Order Type', 'Symbol', 'Side', 'Avg. Filled Price', 'Filled Amount', 'Filled Volume', 'Filled Volume (USDT)', 'Filled Time(UTC)', 'Fee'],
    relatedPatterns: ['fomo-re-entry', 'chasing-momentum', 'overtrading'],
    homepageUrl: 'https://www.kucoin.com',
    foundedYear: 2017,
    headquarters: 'Seychelles',
  },
]

/** Lookup a broker by slug. Returns undefined when no match. */
export function getBroker(slug: string): BrokerInfo | undefined {
  return BROKERS.find((b) => b.slug === slug)
}

/** All slugs — convenient for static-site-generation `generateStaticParams`. */
export function getBrokerSlugs(): string[] {
  return BROKERS.map((b) => b.slug)
}
