/**
 * Glossary registry — single source of truth for /glossary/[slug] SEO pages.
 *
 * Categories:
 *  - metrics: Trading-performance measurements (drawdown, Sharpe, etc.)
 *  - orders: Order types and order-management mechanics
 *  - options: Options-specific terminology
 *  - technical: Technical-analysis indicators and concepts
 *  - psychology: Trading-psychology and behavioural-finance terms
 *  - risk: Risk-management concepts (sizing, leverage, etc.)
 *  - general: Catch-all for cross-cutting trading terms
 *
 * `relatedTerms` slugs MUST exist in this registry; `relatedPatterns`
 * slugs MUST exist in lib/seo/patternRegistry.ts. `slug` is lowercase +
 * hyphenated.
 */

export interface GlossaryTerm {
  slug: string
  term: string
  category: 'metrics' | 'orders' | 'options' | 'technical' | 'psychology' | 'risk' | 'crypto' | 'general'
  shortDef: string
  fullDef: string
  formula?: string
  example: string
  relatedTerms: string[]
  relatedPatterns: string[]
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // ─────────────────────────────────────────────────────────────────
  // METRICS (15)
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'drawdown',
    term: 'Drawdown',
    category: 'metrics',
    shortDef: 'The peak-to-trough decline in account equity, expressed as a percentage of the previous peak.',
    fullDef: 'Drawdown measures how far an account has fallen from its highest equity point before recovering. It is the most direct measure of risk a trader experiences in real time. A 20% drawdown means the account is down 20% from its previous high — and importantly, recovering from a 20% drawdown requires a 25% gain on the smaller capital base. Deep drawdowns also test psychological discipline; most blowups happen during drawdown phases when traders abandon their plan to "make it back."',
    formula: 'Drawdown = (Peak Equity − Current Equity) / Peak Equity × 100%',
    example: 'Account peaks at ₹1,00,000 then drops to ₹80,000. The drawdown is (1,00,000 − 80,000) / 1,00,000 = 20%. To recover to the previous peak, the account needs to gain 25% from the ₹80,000 level (not 20%).',
    relatedTerms: ['max-drawdown', 'recovery-factor', 'calmar-ratio'],
    relatedPatterns: ['hope-and-hold', 'panic-exit', 'revenge-trade'],
  },
  {
    slug: 'win-rate',
    term: 'Win Rate',
    category: 'metrics',
    shortDef: 'The percentage of trades that closed at a profit out of all closed trades.',
    fullDef: 'Win rate is the most-cited but least-useful single metric for evaluating a trading strategy. A 70% win rate sounds impressive but is meaningless without knowing the size of average wins versus average losses — a strategy can have 70% win rate and still lose money if losers are 3x the size of winners. Win rate must always be paired with risk-reward ratio to assess true edge.',
    formula: 'Win Rate = (Number of Winning Trades / Total Trades) × 100%',
    example: 'Out of 100 trades, 55 closed at a profit and 45 at a loss. Win rate = 55/100 = 55%. If average win is ₹500 and average loss is ₹800, the strategy still loses money despite the >50% win rate.',
    relatedTerms: ['profit-factor', 'risk-reward-ratio', 'expectancy', 'average-win', 'average-loss'],
    relatedPatterns: ['disposition-effect', 'gambler-fallacy'],
  },
  {
    slug: 'profit-factor',
    term: 'Profit Factor',
    category: 'metrics',
    shortDef: 'Gross profit divided by gross loss — a single number summary of strategy efficiency.',
    fullDef: 'Profit factor combines win frequency and win/loss size into one ratio. A profit factor of 1.0 means the strategy breaks even before costs. Above 1.5 indicates a robust strategy; above 2.0 is excellent for retail. Values above 3.0 are rare and usually indicate either an exceptional edge or curve-fit results that won\'t hold out of sample.',
    formula: 'Profit Factor = Gross Profit / Gross Loss',
    example: 'Across 100 trades: total profit ₹50,000, total losses ₹25,000. Profit factor = 50,000 / 25,000 = 2.0. The strategy makes ₹2 for every ₹1 risked over its sample.',
    relatedTerms: ['win-rate', 'expectancy', 'average-win', 'average-loss'],
    relatedPatterns: ['disposition-effect', 'premature-exit'],
  },
  {
    slug: 'sharpe-ratio',
    term: 'Sharpe Ratio',
    category: 'metrics',
    shortDef: 'Risk-adjusted return — excess return per unit of total volatility.',
    fullDef: 'Sharpe ratio measures how much return a strategy earns per unit of total risk taken (measured as standard deviation of returns). A Sharpe ratio above 1.0 is considered good; above 2.0 is excellent. The metric penalises both upside and downside volatility equally, which is why some traders prefer Sortino ratio (which only penalises downside). Sharpe is the standard institutional measure of risk-adjusted performance.',
    formula: 'Sharpe Ratio = (Rp − Rf) / σp,  where Rp = portfolio return, Rf = risk-free rate, σp = standard deviation of portfolio returns',
    example: 'Strategy returns 18% annually with 12% volatility. Risk-free rate is 6%. Sharpe = (18 − 6) / 12 = 1.0. The strategy earns one unit of excess return per unit of volatility taken.',
    relatedTerms: ['sortino-ratio', 'calmar-ratio', 'max-drawdown'],
    relatedPatterns: [],
  },
  {
    slug: 'sortino-ratio',
    term: 'Sortino Ratio',
    category: 'metrics',
    shortDef: 'Risk-adjusted return — like Sharpe, but penalising only downside volatility.',
    fullDef: 'Sortino ratio refines Sharpe by recognising that traders don\'t fear upside volatility. It uses downside deviation (standard deviation of negative returns only) in the denominator, so a strategy with consistent winners and occasional big winners isn\'t penalised. Generally considered more relevant for trading evaluation than Sharpe for this reason. Values above 1.5 are considered strong.',
    formula: 'Sortino Ratio = (Rp − Rf) / σd,  where σd = standard deviation of negative returns only',
    example: 'Strategy returns 20% annually. Risk-free rate is 5%. Downside deviation is 8%. Sortino = (20 − 5) / 8 = 1.875. Stronger than its Sharpe would be if upside volatility were also high.',
    relatedTerms: ['sharpe-ratio', 'calmar-ratio'],
    relatedPatterns: [],
  },
  {
    slug: 'expectancy',
    term: 'Expectancy',
    category: 'metrics',
    shortDef: 'The expected profit or loss per trade, on average, over a large sample.',
    fullDef: 'Expectancy is the most decision-useful metric for a strategy because it tells you what each trade is worth in expected value. A positive expectancy strategy makes money over time even if individual trades are random. Expectancy combines win rate and average win/loss into a single per-trade dollar (or ₹) value. Strategies with expectancy below ₹0 lose money over enough trades regardless of how good they "feel."',
    formula: 'Expectancy = (Win Rate × Average Win) − (Loss Rate × Average Loss)',
    example: 'Win rate 45%, average win ₹1,500, average loss ₹800. Expectancy = (0.45 × 1500) − (0.55 × 800) = 675 − 440 = ₹235 per trade. Over 100 trades, expected profit is ₹23,500.',
    relatedTerms: ['win-rate', 'profit-factor', 'average-win', 'average-loss', 'risk-reward-ratio'],
    relatedPatterns: ['disposition-effect', 'overtrading'],
  },
  {
    slug: 'average-win',
    term: 'Average Win',
    category: 'metrics',
    shortDef: 'Mean profit on winning trades — used alongside average loss to compute expectancy.',
    fullDef: 'Average win is the simple mean of all profitable trades over a period. Comparing it to average loss reveals whether the strategy has the right risk-reward asymmetry. A common retail mistake is letting losers run and cutting winners short, which crushes the average-win-to-average-loss ratio below 1.0 and turns even high-win-rate strategies unprofitable.',
    formula: 'Average Win = Sum of profits on winning trades / Number of winning trades',
    example: 'Across 30 winning trades, total profit was ₹45,000. Average win = 45,000 / 30 = ₹1,500.',
    relatedTerms: ['average-loss', 'win-rate', 'expectancy', 'risk-reward-ratio'],
    relatedPatterns: ['premature-exit', 'disposition-effect'],
  },
  {
    slug: 'average-loss',
    term: 'Average Loss',
    category: 'metrics',
    shortDef: 'Mean loss on losing trades — paired with average win to assess risk-reward asymmetry.',
    fullDef: 'Average loss is the mean dollar amount lost on losing trades. The ratio of average win to average loss is one of the most important diagnostics in retail trading: when this ratio drops below 1.0, the strategy needs a >50% win rate just to break even. A healthy ratio is 1.5-2.0 — meaning your typical winner is 1.5-2x larger than your typical loser.',
    formula: 'Average Loss = Sum of losses on losing trades / Number of losing trades',
    example: 'Across 25 losing trades, total loss was ₹20,000. Average loss = 20,000 / 25 = ₹800.',
    relatedTerms: ['average-win', 'win-rate', 'expectancy', 'risk-reward-ratio'],
    relatedPatterns: ['hope-and-hold', 'ignoring-stop-loss'],
  },
  {
    slug: 'largest-win',
    term: 'Largest Win',
    category: 'metrics',
    shortDef: 'The single biggest profit in the trading record — informative about strategy upside and skew.',
    fullDef: 'Largest win is a useful diagnostic when paired with average win. If the largest win is dramatically larger than the median win, the strategy\'s profitability may be concentrated in a few outsized trades — which is risky because those few trades may not repeat. Healthy strategies have a relatively flat distribution of wins.',
    example: 'Across 30 winning trades, the largest single win is ₹8,000 while the median is ₹1,200. The strategy is heavily reliant on that one outlier.',
    relatedTerms: ['largest-loss', 'average-win', 'expectancy'],
    relatedPatterns: [],
  },
  {
    slug: 'largest-loss',
    term: 'Largest Loss',
    category: 'metrics',
    shortDef: 'The single biggest loss — a critical diagnostic for risk management discipline.',
    fullDef: 'Largest loss tells you the worst single outcome the strategy has produced. A strategy where the largest loss is 3-5x the average loss often indicates ignored stop-losses or position-size blowouts. A well-disciplined strategy should have largest loss within roughly 1.5x of the average loss — if not, risk management is the highest-leverage thing to fix.',
    example: 'Average loss is ₹800; largest loss is ₹5,000. The 6x ratio strongly suggests one or more stop-losses were ignored or position size was wrong on that trade.',
    relatedTerms: ['largest-win', 'average-loss', 'max-drawdown'],
    relatedPatterns: ['ignoring-stop-loss', 'averaging-down', 'panic-exit'],
  },
  {
    slug: 'risk-reward-ratio',
    term: 'Risk-Reward Ratio',
    category: 'metrics',
    shortDef: 'The ratio of expected profit to potential loss on a single trade — usually expressed as e.g. "1:2".',
    fullDef: 'Risk-reward ratio (R:R or RR) measures how much you stand to make versus how much you risk on a trade. A 1:2 ratio means you risk ₹1 to make ₹2; a 1:0.5 ratio means you risk ₹2 to make ₹1. Strategies with R:R below 1:1 require >50% win rate just to break even before costs. R:R is the easiest variable to control: by setting the stop and target levels, you decide R:R before entering. Many losing retail strategies have R:R below 1:1 combined with sub-50% win rate — guaranteed unprofitable.',
    formula: 'R:R = Distance to Target / Distance to Stop  (often written as 1:N where N is the multiple)',
    example: 'Entry ₹100, stop ₹98, target ₹104. Distance to stop = ₹2, distance to target = ₹4. R:R = 4/2 = 2.0, written as 1:2.',
    relatedTerms: ['expectancy', 'win-rate', 'take-profit', 'stop-order', 'average-win', 'average-loss'],
    relatedPatterns: ['premature-exit', 'disposition-effect', 'larger-position'],
  },
  {
    slug: 'max-drawdown',
    term: 'Max Drawdown',
    category: 'metrics',
    shortDef: 'The largest peak-to-trough drawdown ever experienced by the account or strategy.',
    fullDef: 'Max drawdown is the worst-case historical decline. It is a critical input for psychological capacity planning: if your strategy has a 30% historical max drawdown, you must be able to stomach 30% (or more) drawdowns going forward, because future drawdowns may exceed historical ones. Many traders quit during drawdowns smaller than their strategy\'s historical max because they hadn\'t planned for that pain.',
    formula: 'Max Drawdown = max over all periods of (Peak Equity − Trough Equity) / Peak Equity',
    example: 'Account ran from ₹1,00,000 to ₹1,20,000, dropped to ₹85,000, recovered to ₹1,30,000. Max drawdown was (1,20,000 − 85,000) / 1,20,000 = 29.2%.',
    relatedTerms: ['drawdown', 'recovery-factor', 'calmar-ratio', 'sharpe-ratio'],
    relatedPatterns: ['panic-exit', 'revenge-trade', 'hope-and-hold'],
  },
  {
    slug: 'recovery-factor',
    term: 'Recovery Factor',
    category: 'metrics',
    shortDef: 'Net profit divided by max drawdown — how efficiently a strategy recovers from worst losses.',
    fullDef: 'Recovery factor measures how much profit a strategy generates per unit of worst-case drawdown experienced. A recovery factor of 3.0 means net profit is 3x the max drawdown — robust. Below 1.0 means the strategy has not yet generated enough profit to justify the worst-case pain it inflicts; this often happens early in a strategy\'s life or when drawdown is unusually severe.',
    formula: 'Recovery Factor = Net Profit / Max Drawdown',
    example: 'Strategy generated ₹1,50,000 net profit with a max drawdown of ₹30,000. Recovery factor = 1,50,000 / 30,000 = 5.0. For every ₹1 of worst-case drawdown, the strategy has produced ₹5 of net profit.',
    relatedTerms: ['max-drawdown', 'sharpe-ratio', 'calmar-ratio'],
    relatedPatterns: [],
  },
  {
    slug: 'calmar-ratio',
    term: 'Calmar Ratio',
    category: 'metrics',
    shortDef: 'Annualised return divided by max drawdown — risk-adjusted return using worst-case decline.',
    fullDef: 'Calmar ratio is similar in spirit to Sharpe but uses max drawdown instead of standard deviation as the risk measure. This makes it more relevant to traders who care about psychological pain (drawdowns) more than statistical volatility. Calmar above 0.5 is reasonable; above 1.0 is good; above 3.0 is excellent and rare.',
    formula: 'Calmar Ratio = Annualised Return / Max Drawdown',
    example: 'Strategy returned 24% annualised with a 12% max drawdown. Calmar = 24 / 12 = 2.0.',
    relatedTerms: ['sharpe-ratio', 'sortino-ratio', 'max-drawdown', 'recovery-factor'],
    relatedPatterns: [],
  },
  {
    slug: 'streak-length',
    term: 'Streak Length',
    category: 'metrics',
    shortDef: 'The number of consecutive winning or losing trades — a useful measure of variance and psychological pressure.',
    fullDef: 'Streak length measures the longest consecutive sequence of wins or losses. Even a 60% win-rate strategy will produce 5+ losing streaks regularly. Knowing your strategy\'s historical streak distribution prevents the gambler\'s fallacy of believing "the run has to end" or sizing up after wins. Position sizing should be calibrated to survive the worst historical losing streak.',
    example: 'Strategy with 55% win rate over 200 trades had a longest losing streak of 7 and a longest winning streak of 9. Position sizing should be small enough that 7 consecutive losses do not cause panic.',
    relatedTerms: ['win-rate', 'expectancy', 'max-drawdown'],
    relatedPatterns: ['gambler-fallacy', 'hot-hand-fallacy', 'revenge-trade'],
  },

  // ─────────────────────────────────────────────────────────────────
  // ORDERS (12)
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'market-order',
    term: 'Market Order',
    category: 'orders',
    shortDef: 'An order to buy or sell immediately at the best available current price.',
    fullDef: 'Market orders prioritise execution certainty over price certainty: the order will fill, but the fill price depends on what the market is offering at that instant. Best used for highly liquid instruments where the spread is tight; worst used during volatile news events when slippage can be substantial. Most retail brokers default to market orders, but limit orders are usually better for non-urgent entries.',
    example: 'You place a market buy order for 100 shares of AAPL when the bid is $150.00 and the ask is $150.05. Your order fills at $150.05 (the ask) immediately.',
    relatedTerms: ['limit-order', 'slippage', 'spread'],
    relatedPatterns: ['fomo-re-entry', 'chasing-momentum'],
  },
  {
    slug: 'limit-order',
    term: 'Limit Order',
    category: 'orders',
    shortDef: 'An order to buy or sell only at a specified price or better — execution is not guaranteed.',
    fullDef: 'A limit order specifies the maximum price you\'ll pay (for buys) or minimum price you\'ll accept (for sells). The order rests in the book until either filled at your price (or better) or cancelled. Limit orders eliminate slippage but accept the risk of non-execution if the market moves away. Strongly preferred for entries at planned levels — especially in less-liquid instruments or fast markets.',
    example: 'You place a limit buy order at ₹495 for a stock currently trading at ₹500. The order fills only if the stock drops to ₹495 or lower. If it rallies instead, the order never fills.',
    relatedTerms: ['market-order', 'stop-limit', 'gtc', 'day-order'],
    relatedPatterns: ['late-entry', 'chasing-momentum'],
  },
  {
    slug: 'stop-order',
    term: 'Stop Order',
    category: 'orders',
    shortDef: 'An order that becomes a market order when a specified trigger price is reached.',
    fullDef: 'Stop orders are dormant until the trigger price prints, after which they convert to market orders for immediate execution. Used most commonly as stop-loss orders to limit downside. Because they convert to market orders, they\'re subject to slippage during fast moves — gaps over the stop price can result in fills materially below the stop. Stop-limit orders mitigate this at the cost of execution certainty.',
    example: 'Long position at ₹500, stop-loss at ₹490. When price prints ₹490 or lower, the stop converts to a market sell order. In a normal market it fills near ₹490; in a gap, it might fill at ₹485.',
    relatedTerms: ['stop-limit', 'trailing-stop', 'take-profit', 'oco-order', 'slippage'],
    relatedPatterns: ['ignoring-stop-loss', 'panic-exit', 'hope-and-hold'],
  },
  {
    slug: 'stop-limit',
    term: 'Stop-Limit Order',
    category: 'orders',
    shortDef: 'A stop order that converts to a limit order (instead of a market order) when triggered.',
    fullDef: 'Stop-limit orders combine the trigger of a stop with the price-control of a limit. When the stop price is hit, the order becomes a limit order at the specified limit price. This protects against slippage in fast markets but introduces the risk that price keeps moving past the limit and the order never fills — leaving you with unprotected losses. Use carefully in volatile instruments.',
    example: 'Stop ₹490, limit ₹489. If price hits ₹490, a limit sell at ₹489 is placed. If price drops straight to ₹485 with no fills at ₹489, the stop-limit doesn\'t execute and you stay long.',
    relatedTerms: ['stop-order', 'limit-order', 'slippage'],
    relatedPatterns: ['ignoring-stop-loss'],
  },
  {
    slug: 'trailing-stop',
    term: 'Trailing Stop',
    category: 'orders',
    shortDef: 'A stop order that adjusts in the direction of profit as price moves favourably — never against the position.',
    fullDef: 'A trailing stop sets a fixed distance (in points or percent) below (for longs) or above (for shorts) the current price. As the price moves favourably, the stop ratchets to follow at that distance. If the price moves adversely, the stop stays put. This lets winning trades run while protecting gains, addressing the common premature-exit problem.',
    example: 'Long at ₹500 with a 2% trailing stop. Stop initially at ₹490. Price rallies to ₹520; stop trails to ₹509.6. Price reverses to ₹510; stop stays at ₹509.6 and triggers, locking ₹9.6/share gain.',
    relatedTerms: ['stop-order', 'take-profit', 'risk-reward-ratio', 'atr'],
    relatedPatterns: ['premature-exit', 'disposition-effect'],
  },
  {
    slug: 'take-profit',
    term: 'Take-Profit',
    category: 'orders',
    shortDef: 'A pre-set order to exit a profitable position at a specified favourable price.',
    fullDef: 'Take-profit (TP) orders are limit orders set above the entry (for longs) or below (for shorts) at the planned profit-taking level. They remove emotion from the exit decision by pre-committing to a level. Combined with a stop-loss in an OCO order, they create a hands-off trade-management system. The pre-defined target also forces the trader to think about risk-reward before entry.',
    example: 'Buy ₹500, target ₹520 (4% profit). Take-profit limit sell placed at ₹520. When price prints ₹520, the position closes automatically with a ₹20/share gain.',
    relatedTerms: ['limit-order', 'stop-order', 'oco-order', 'bracket-order', 'risk-reward-ratio'],
    relatedPatterns: ['premature-exit', 'anchoring-bias'],
  },
  {
    slug: 'oco-order',
    term: 'OCO Order',
    category: 'orders',
    shortDef: 'One-Cancels-the-Other: a paired order where executing one side automatically cancels the other.',
    fullDef: 'OCO orders bundle a stop-loss and a take-profit into a single linked structure. When either side executes, the other is cancelled automatically. This prevents the trader from accidentally being stopped out and then having the take-profit hit a position they no longer hold. Essential for any disciplined trade-management workflow.',
    example: 'Long at ₹500. OCO with stop at ₹490 and target at ₹520. If price drops to ₹490, the stop executes and the ₹520 target is cancelled. If price rallies to ₹520, the target executes and the ₹490 stop is cancelled.',
    relatedTerms: ['stop-order', 'take-profit', 'bracket-order'],
    relatedPatterns: ['ignoring-stop-loss', 'hope-and-hold'],
  },
  {
    slug: 'bracket-order',
    term: 'Bracket Order',
    category: 'orders',
    shortDef: 'An entry order paired with a stop-loss and take-profit, all submitted together.',
    fullDef: 'Bracket orders combine three orders into one workflow: an entry order, a stop-loss, and a take-profit. When the entry fills, the bracket activates the stop and target as an OCO pair. This forces the trader to define stop and target before entering, addressing the common error of entering "to see how it goes" with no exit plan.',
    example: 'Bracket buy at ₹500 with stop ₹490 and target ₹520. When the entry fills, the OCO of ₹490 stop and ₹520 target activates immediately. Trade is fully managed before any further attention is needed.',
    relatedTerms: ['oco-order', 'stop-order', 'take-profit', 'risk-reward-ratio'],
    relatedPatterns: ['ignoring-stop-loss'],
  },
  {
    slug: 'iceberg-order',
    term: 'Iceberg Order',
    category: 'orders',
    shortDef: 'A large order split into smaller visible chunks to hide total size from the market.',
    fullDef: 'Iceberg orders display only a fraction of the total order size in the book; as visible chunks fill, the next chunk is automatically displayed. Used by institutions to avoid moving the market when executing large positions. Most retail traders won\'t use these directly but should know they exist — they explain why "thin" books sometimes absorb large fills without obvious size showing.',
    example: 'Iceberg sell of 10,000 shares with display size of 500. Only 500 shares show in the book. As they fill, the next 500 are displayed, and so on, until the full 10,000 is sold without ever showing more than 500 at once.',
    relatedTerms: ['limit-order', 'market-order'],
    relatedPatterns: [],
  },
  {
    slug: 'gtc',
    term: 'GTC (Good-Till-Cancelled)',
    category: 'orders',
    shortDef: 'An order that remains active until explicitly cancelled or filled, often with a 90-day broker maximum.',
    fullDef: 'GTC orders persist across trading sessions until executed or cancelled. Most brokers cap GTC at 60-90 days. Useful for setting limit orders at structural levels you may take if reached over weeks. Risk: a forgotten GTC can fire unexpectedly during a news-driven move and leave you with an unwanted position.',
    example: 'You place a GTC buy limit at ₹450 for a stock trading at ₹500. Two weeks later the stock drops to ₹450 on news; your order fills automatically. If you forgot about it, you now own the position.',
    relatedTerms: ['day-order', 'limit-order', 'ioc-order'],
    relatedPatterns: [],
  },
  {
    slug: 'day-order',
    term: 'Day Order',
    category: 'orders',
    shortDef: 'An order that automatically expires at the end of the current trading session if not filled.',
    fullDef: 'Day orders are the default at most brokers. They are active during regular trading hours and cancelled automatically at the close. Useful for intraday setups where carrying the order overnight doesn\'t fit the strategy. Always confirm whether your broker\'s default is day or GTC — getting this wrong has caused many "phantom fills" the next morning.',
    example: 'You place a day-order buy limit at ₹495 for a stock currently at ₹500. By close it hadn\'t reached ₹495. The order auto-cancels. The next day if the stock drops to ₹495, no fill occurs.',
    relatedTerms: ['gtc', 'limit-order', 'ioc-order'],
    relatedPatterns: [],
  },
  {
    slug: 'ioc-order',
    term: 'IOC (Immediate-Or-Cancel)',
    category: 'orders',
    shortDef: 'An order that fills as much as possible immediately and cancels any unfilled remainder.',
    fullDef: 'IOC orders attempt immediate execution and cancel any unfilled portion. Useful when you want a partial fill but don\'t want resting orders sitting in the book. A subset variant — Fill-Or-Kill (FOK) — requires the entire order to fill immediately or cancel completely with no partial fills.',
    example: 'IOC buy 1000 shares at ₹100 limit. The book has 600 shares offered at ₹100. The IOC fills 600 shares immediately and cancels the unfilled 400.',
    relatedTerms: ['day-order', 'gtc', 'limit-order'],
    relatedPatterns: [],
  },

  // ─────────────────────────────────────────────────────────────────
  // OPTIONS (14)
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'call-option',
    term: 'Call Option',
    category: 'options',
    shortDef: 'A contract giving the holder the right (not obligation) to buy an asset at a specified price by a specified date.',
    fullDef: 'A call option gives the buyer the right to purchase the underlying at the strike price on or before expiry. The buyer pays a premium for this right. Calls are profitable when the underlying rises above the strike plus premium paid. Used both as bullish bets and as part of more complex strategies (covered calls, spreads). Maximum loss for a long call buyer is the premium paid.',
    example: 'NIFTY 24500 CE bought at ₹120 premium with NIFTY at 24400. If NIFTY rallies to 24700 by expiry, intrinsic value = 24700 − 24500 = ₹200. Net profit = 200 − 120 = ₹80 per lot. If NIFTY stays below 24500, the call expires worthless and the ₹120 premium is lost.',
    relatedTerms: ['put-option', 'strike-price', 'expiry-date', 'premium', 'intrinsic-value'],
    relatedPatterns: ['fomo-re-entry', 'chasing-momentum'],
  },
  {
    slug: 'put-option',
    term: 'Put Option',
    category: 'options',
    shortDef: 'A contract giving the holder the right (not obligation) to sell an asset at a specified price by a specified date.',
    fullDef: 'A put option gives the buyer the right to sell the underlying at the strike price on or before expiry. The buyer pays a premium for downside protection or speculation. Puts profit when the underlying falls below the strike minus premium. Used as portfolio hedges, bearish bets, or the long leg of bear spreads. Maximum loss for a long put buyer is the premium paid.',
    example: 'NIFTY 24300 PE bought at ₹90 premium with NIFTY at 24400. If NIFTY drops to 24100 by expiry, intrinsic value = 24300 − 24100 = ₹200. Net profit = 200 − 90 = ₹110 per lot. If NIFTY stays above 24300, the put expires worthless.',
    relatedTerms: ['call-option', 'strike-price', 'expiry-date', 'premium', 'intrinsic-value'],
    relatedPatterns: ['fomo-re-entry'],
  },
  {
    slug: 'strike-price',
    term: 'Strike Price',
    category: 'options',
    shortDef: 'The pre-agreed price at which the option holder can exercise — buy (call) or sell (put) the underlying.',
    fullDef: 'The strike price is the fixed reference price baked into the option contract. It determines whether an option is in-the-money (ITM), at-the-money (ATM), or out-of-the-money (OTM) at any given underlying price. ATM strikes have the highest absolute time value; ITM strikes have the most intrinsic value; OTM strikes are pure time value with no intrinsic value.',
    example: 'NIFTY at 24450. The 24500 CE has a strike of 24500 (slightly OTM). The 24400 CE has a strike of 24400 (ITM by 50 points). The 24450 CE is ATM.',
    relatedTerms: ['call-option', 'put-option', 'intrinsic-value', 'time-decay', 'delta'],
    relatedPatterns: [],
  },
  {
    slug: 'expiry-date',
    term: 'Expiry Date',
    category: 'options',
    shortDef: 'The date after which the option contract no longer exists — value at expiry is purely intrinsic.',
    fullDef: 'Every option has a finite life. At expiry, the option is exercised if it is ITM (and worth its intrinsic value) or expires worthless if OTM. As expiry approaches, time value (theta) decays — slowly far from expiry, then accelerating in the final days. Trading near expiry is high-leverage: small moves in the underlying produce large percentage changes in option value but the time decay makes wrong directional bets devastating.',
    example: 'NIFTY weekly options expire every Thursday. A NIFTY 24500 CE bought on Monday for ₹100 may decay to ₹40 by Wednesday afternoon if the underlying doesn\'t move, even though the strike is unchanged.',
    relatedTerms: ['time-decay', 'theta', 'strike-price', 'intrinsic-value'],
    relatedPatterns: ['averaging-down', 'hope-and-hold'],
  },
  {
    slug: 'premium',
    term: 'Premium',
    category: 'options',
    shortDef: 'The market price of an option — what the buyer pays the seller for the contract.',
    fullDef: 'The premium is the option\'s current market price, composed of intrinsic value (if any) plus time value. Premium reflects the market\'s probability-weighted expectation of where the underlying will go before expiry. Implied volatility, time-to-expiry, distance to strike, and interest rates all contribute. As expiry nears and the underlying remains static, premium decays toward intrinsic value (toward zero for OTM options).',
    example: 'NIFTY 24500 CE trades at ₹120 premium with NIFTY at 24450. Intrinsic value = max(0, 24450 − 24500) = ₹0. Time value = 120 − 0 = ₹120. The entire premium is time value; the option is OTM.',
    relatedTerms: ['intrinsic-value', 'time-decay', 'theta', 'implied-volatility'],
    relatedPatterns: [],
  },
  {
    slug: 'intrinsic-value',
    term: 'Intrinsic Value',
    category: 'options',
    shortDef: 'The portion of an option\'s premium that comes from being in-the-money — the immediate exercise value.',
    fullDef: 'Intrinsic value is what an option would be worth if exercised immediately. For a call, it equals max(0, underlying − strike). For a put, it equals max(0, strike − underlying). OTM options have zero intrinsic value — their entire premium is time value, which decays to zero by expiry. ITM options retain at least their intrinsic value at expiry regardless of decay.',
    formula: 'Call intrinsic = max(0, Spot − Strike);  Put intrinsic = max(0, Strike − Spot)',
    example: 'NIFTY at 24600. The 24500 CE has intrinsic value = max(0, 24600 − 24500) = ₹100. The 24700 CE has intrinsic value = max(0, 24600 − 24700) = ₹0 (OTM).',
    relatedTerms: ['premium', 'strike-price', 'time-decay', 'theta'],
    relatedPatterns: [],
  },
  {
    slug: 'time-decay',
    term: 'Time Decay',
    category: 'options',
    shortDef: 'The erosion of an option\'s premium as expiry approaches — measured by theta.',
    fullDef: 'Time decay is the steady loss of an option\'s time value as expiry nears. It accelerates non-linearly: an option loses far more value in its final week than in any prior week. For OTM options, time decay is the primary determinant of value once direction is decided. Long option holders pay this decay; short option sellers collect it.',
    example: 'NIFTY 24500 CE 14 days from expiry trades at ₹120. With NIFTY unchanged, the same option 7 days later might trade at ₹70 — losing ₹50 to theta. With 1 day left, it might be ₹15 even with NIFTY still unchanged.',
    relatedTerms: ['theta', 'premium', 'intrinsic-value', 'expiry-date'],
    relatedPatterns: ['hope-and-hold', 'averaging-down'],
  },
  {
    slug: 'delta',
    term: 'Delta',
    category: 'options',
    shortDef: 'The rate of change in option premium per unit change in the underlying — how option-like vs stock-like the position is.',
    fullDef: 'Delta is the first Greek: it measures the sensitivity of option price to underlying price. Calls have delta from 0 to +1; puts from -1 to 0. ATM options have delta near ±0.5; deep ITM options approach ±1; deep OTM approach 0. Delta also approximates the probability the option finishes ITM at expiry. Used for sizing, hedging, and directional exposure measurement.',
    example: 'NIFTY 24500 CE with delta 0.5 means a ₹100-point NIFTY move adds approximately ₹50 to the option premium. A delta-1.0 deep-ITM call moves rupee-for-rupee with the underlying.',
    relatedTerms: ['gamma', 'theta', 'vega', 'implied-volatility'],
    relatedPatterns: [],
  },
  {
    slug: 'gamma',
    term: 'Gamma',
    category: 'options',
    shortDef: 'The rate of change in delta per unit change in the underlying — the curvature of option pricing.',
    fullDef: 'Gamma is the second derivative of option price with respect to underlying. It tells you how delta itself will move as the underlying moves. Gamma is highest for ATM options near expiry and decays as options move ITM or OTM. High gamma means small underlying moves cause large delta swings — explosive for buyers, terrifying for short sellers. The "gamma squeeze" phenomenon in retail markets is driven by this.',
    example: 'NIFTY 24500 CE with delta 0.5 and gamma 0.04. If NIFTY rises 100 points, new delta is approximately 0.5 + (100 × 0.04 / 100) = 0.54. The option becomes more directional with each move toward and through the strike.',
    relatedTerms: ['delta', 'theta', 'vega'],
    relatedPatterns: [],
  },
  {
    slug: 'theta',
    term: 'Theta',
    category: 'options',
    shortDef: 'The rate of premium decay per day — the cost of holding a long option position over time.',
    fullDef: 'Theta quantifies time decay as a daily premium loss (negative for long options, positive for short option sellers). Theta accelerates as expiry approaches and is highest for ATM options. Strategies like covered calls and credit spreads aim to collect positive theta; long-option speculation must overcome negative theta with directional movement.',
    example: 'NIFTY 24500 CE has theta -2.50. With everything else unchanged, the option will lose approximately ₹2.50 in premium per calendar day. Over a weekend (3 days), expect ₹7.50 of decay.',
    relatedTerms: ['delta', 'gamma', 'vega', 'time-decay', 'expiry-date'],
    relatedPatterns: ['hope-and-hold'],
  },
  {
    slug: 'vega',
    term: 'Vega',
    category: 'options',
    shortDef: 'The change in option premium per 1% change in implied volatility — sensitivity to volatility shifts.',
    fullDef: 'Vega measures how option price responds to changes in implied volatility. Long options have positive vega (gain when IV rises); short options have negative vega. Vega is highest for ATM options and longer-dated options. A volatility crush (IV dropping after an event) destroys long-option value even when the underlying moves favourably — a common surprise for traders buying calls before earnings.',
    example: 'NIFTY 24500 CE with vega 8 means a 1% rise in implied volatility adds ₹8 to the option price. Conversely, after a major event when IV drops 5%, the option loses ₹40 even if the underlying is unchanged.',
    relatedTerms: ['delta', 'gamma', 'theta', 'implied-volatility'],
    relatedPatterns: [],
  },
  {
    slug: 'implied-volatility',
    term: 'Implied Volatility',
    category: 'options',
    shortDef: 'The market\'s expectation of future price volatility, derived from current option prices.',
    fullDef: 'Implied volatility (IV) is the volatility input that, plugged into an option-pricing model, reproduces the option\'s observed market price. High IV means the market expects large moves; low IV means small moves. IV typically rises before binary events (earnings, rate decisions) and crashes after them — the "vol crush." Trading options without understanding IV is one of the most common retail leaks.',
    example: 'NIFTY 24500 CE trading with 25% IV implies the market expects NIFTY to move within roughly ±25% (annualised) from current levels. Same option with 40% IV is significantly more expensive — the market expects bigger swings.',
    relatedTerms: ['vega', 'premium', 'time-decay'],
    relatedPatterns: [],
  },
  {
    slug: 'open-interest',
    term: 'Open Interest',
    category: 'options',
    shortDef: 'The total number of outstanding option contracts at a given strike — a measure of strike-level commitment.',
    fullDef: 'Open interest (OI) counts the contracts that exist at each strike, in contrast to volume which counts only contracts traded today. Rising OI alongside rising premium suggests new buyers entering. Falling OI suggests existing positions closing. OI builds at strikes where the market has commitment; large OI strikes often act as price magnets near expiry.',
    example: 'NIFTY 24500 CE has 5,00,000 contracts of OI; 24700 CE has 1,00,000 OI. The 24500 strike is far more crowded — closing prints near it can have outsized impact on retail option holders.',
    relatedTerms: ['put-call-ratio', 'strike-price', 'premium'],
    relatedPatterns: [],
  },
  {
    slug: 'put-call-ratio',
    term: 'Put-Call Ratio',
    category: 'options',
    shortDef: 'Ratio of put open interest (or volume) to call open interest — a sentiment indicator.',
    fullDef: 'PCR compares put activity to call activity. PCR above 1 suggests bearish sentiment (more puts than calls); below 1 suggests bullish. As a contrarian indicator, extreme PCR readings often mark turning points: very high PCR after a sell-off suggests capitulation; very low PCR after a rally suggests complacency. PCR alone is not a setup but useful as one input.',
    formula: 'PCR = Put OI / Call OI  (or Put Volume / Call Volume)',
    example: 'NIFTY total put OI = 12,00,000; call OI = 8,00,000. PCR = 12/8 = 1.5. Bearish skew, often interpreted as either confirmation of a downtrend or a contrarian "too many puts, mean reversion likely" signal.',
    relatedTerms: ['open-interest', 'implied-volatility'],
    relatedPatterns: ['herd-behavior'],
  },

  // ─────────────────────────────────────────────────────────────────
  // TECHNICAL (13)
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'support',
    term: 'Support',
    category: 'technical',
    shortDef: 'A price level at which buying interest historically exceeds selling pressure — a floor where price tends to bounce.',
    fullDef: 'Support is identified by prior swing lows, accumulation zones, or higher-timeframe pivots where price has reversed upward multiple times. The more times a level holds, the stronger it is — until it breaks, after which it often becomes resistance. Used for entries on bounces or as stop-loss reference for long trades.',
    example: 'NIFTY has bounced from 24300 four times in two weeks, making it strong support. A long entry at 24310 with stop just below 24290 has a tight asymmetric risk-reward if the level holds again.',
    relatedTerms: ['resistance', 'breakout', 'fakeout', 'pivot-points'],
    relatedPatterns: ['late-entry', 'chasing-momentum'],
  },
  {
    slug: 'resistance',
    term: 'Resistance',
    category: 'technical',
    shortDef: 'A price level at which selling interest historically exceeds buying pressure — a ceiling where price tends to reject.',
    fullDef: 'Resistance is the mirror of support: prior swing highs or distribution zones where supply repeatedly overwhelms demand. Strong resistance typically requires multiple rejections to confirm. When broken decisively, former resistance often becomes new support. Used for short entries, profit targets on long trades, or fade setups in ranging markets.',
    example: 'NIFTY has rejected at 25000 three times in a month — strong resistance. A short scalp at 24990 with stop at 25020 plays the rejection. If price closes above 25020 with volume, the level is broken and now a long bias is favoured.',
    relatedTerms: ['support', 'breakout', 'fakeout', 'pivot-points'],
    relatedPatterns: ['late-entry'],
  },
  {
    slug: 'breakout',
    term: 'Breakout',
    category: 'technical',
    shortDef: 'A move where price decisively exits a prior range, support, or resistance level — often with volume confirmation.',
    fullDef: 'A breakout signals the start of a new trend or extension of an existing one. Quality breakouts are decisive (no quick reversal back into the range), volume-confirmed (large participation), and from a meaningful structural level. The first pullback after a breakout often offers the best entry — chasing the initial breakout itself is a common FOMO trap.',
    example: 'NIFTY has ranged 24400-24600 for two weeks. It closes at 24620 on heavy volume, breaking the upper bound. A long entry on the first pullback to 24600 (former resistance, now support) is a textbook breakout-retest play.',
    relatedTerms: ['support', 'resistance', 'fakeout', 'moving-average'],
    relatedPatterns: ['fomo-re-entry', 'chasing-momentum', 'late-entry'],
  },
  {
    slug: 'fakeout',
    term: 'Fakeout',
    category: 'technical',
    shortDef: 'A failed breakout — price briefly exits a level then quickly reverses back inside, often trapping breakout buyers.',
    fullDef: 'Fakeouts are common at obvious levels, especially in ranging markets. Price prints just beyond support or resistance to trigger stop orders or breakout entries, then snaps back. A fakeout that closes back inside the prior range on the same candle is a powerful reversal signal. Recognising them early saves traders from the worst breakout-chase losses.',
    example: 'NIFTY breaks 24600 resistance to 24615 — breakout buyers enter — then collapses to 24580 within 15 minutes. The breakout was a fakeout. Late breakout buyers are now underwater and will likely contribute to the next leg down.',
    relatedTerms: ['breakout', 'support', 'resistance'],
    relatedPatterns: ['fomo-re-entry', 'chasing-momentum', 'late-entry'],
  },
  {
    slug: 'rsi',
    term: 'RSI (Relative Strength Index)',
    category: 'technical',
    shortDef: 'A 0-100 momentum oscillator — readings above 70 traditionally signal overbought, below 30 oversold.',
    fullDef: 'RSI measures the velocity and magnitude of price movements over a lookback period (typically 14 bars). Above 70 suggests momentum is stretched to the upside; below 30 to the downside. RSI divergence — price making new highs while RSI fails to — is one of the most reliable reversal signals. Used for confirmation of trend exhaustion and counter-trend entry timing.',
    formula: 'RSI = 100 − [100 / (1 + (Average Gain / Average Loss))],  where averages are over the lookback window',
    example: 'A stock rallies from ₹100 to ₹120 over 14 bars with strong volume. RSI reads 78 — overbought territory. A pullback to support is statistically more likely than continuation; the trader waits or shorts the rejection.',
    relatedTerms: ['macd', 'moving-average', 'bollinger-bands'],
    relatedPatterns: ['confirmation-bias'],
  },
  {
    slug: 'macd',
    term: 'MACD',
    category: 'technical',
    shortDef: 'Moving Average Convergence Divergence — a trend-following momentum indicator using two moving averages.',
    fullDef: 'MACD plots the difference between a fast EMA (typically 12-period) and a slow EMA (26-period), with a signal line (9-period EMA of MACD) overlaid. Bullish crossovers (MACD above signal line) suggest upward momentum; bearish crossovers, downward. The histogram shows the gap between MACD and signal — useful for spotting momentum shifts before crossovers complete. Like RSI, divergence between MACD and price is a powerful reversal signal.',
    formula: 'MACD = EMA(12) − EMA(26);  Signal = EMA(9) of MACD;  Histogram = MACD − Signal',
    example: 'A stock\'s MACD line crosses above its signal line while the histogram flips positive after weeks of being negative. This bullish crossover often precedes a multi-day uptrend.',
    relatedTerms: ['rsi', 'moving-average', 'ema'],
    relatedPatterns: ['confirmation-bias'],
  },
  {
    slug: 'bollinger-bands',
    term: 'Bollinger Bands',
    category: 'technical',
    shortDef: 'A volatility envelope around a moving average — bands widen during high volatility and contract during calm.',
    fullDef: 'Bollinger Bands plot a 20-period SMA with bands at ±2 standard deviations. About 95% of price action stays within the bands; touches of the upper band suggest stretched upside, lower band stretched downside. A "Bollinger squeeze" — bands narrowing dramatically — often precedes large breakout moves. Used for mean-reversion entries and volatility forecasting.',
    formula: 'Upper Band = SMA(20) + 2σ;  Lower Band = SMA(20) − 2σ',
    example: 'A stock trades inside its Bollinger Bands for two weeks, with bands gradually narrowing — the squeeze. On the next session, a large breakout candle pierces the upper band with high volume. The squeeze release often runs for several days.',
    relatedTerms: ['moving-average', 'sma', 'atr'],
    relatedPatterns: ['chasing-momentum'],
  },
  {
    slug: 'moving-average',
    term: 'Moving Average',
    category: 'technical',
    shortDef: 'A line plotting the average price over a rolling window — smooths noise to reveal trend direction.',
    fullDef: 'A moving average (MA) takes the mean of closing prices over the last N bars. Price above the MA suggests uptrend; below suggests downtrend. MAs are widely used as dynamic support/resistance and as crossover signals (e.g., 50 MA crossing above 200 MA = "golden cross"). The two main flavours are SMA (simple, equal weighting) and EMA (exponential, recent prices weighted more).',
    example: 'NIFTY trades at 24800 with the 50-day SMA at 24400 and 200-day at 23900. Price is in clear uptrend with both MAs sloping up. Pullbacks to the 50 MA often offer trend-aligned long entries.',
    relatedTerms: ['ema', 'sma', 'macd', 'bollinger-bands'],
    relatedPatterns: ['recency-bias'],
  },
  {
    slug: 'ema',
    term: 'EMA (Exponential Moving Average)',
    category: 'technical',
    shortDef: 'A moving average that weights recent prices more heavily, reacting faster to changes than SMA.',
    fullDef: 'EMA applies a multiplier so recent prices contribute more to the average than older prices. The result is a faster, more responsive line — useful for shorter-term setups but more prone to whipsaws than SMA. The 20 EMA and 50 EMA are common choices for intraday and swing trading respectively. Crossovers between fast and slow EMAs are popular trend signals.',
    formula: 'EMA(today) = (Close × multiplier) + EMA(yesterday) × (1 − multiplier);  multiplier = 2 / (N + 1)',
    example: 'A stock\'s 20 EMA is at ₹500 while the 50 EMA is at ₹490. Price pulls back to ₹502. The 20 EMA acts as dynamic support; many traders buy this kind of pullback in confirmed uptrends.',
    relatedTerms: ['sma', 'moving-average', 'macd'],
    relatedPatterns: [],
  },
  {
    slug: 'sma',
    term: 'SMA (Simple Moving Average)',
    category: 'technical',
    shortDef: 'A moving average computed as a straight arithmetic mean of the last N closing prices.',
    fullDef: 'SMA gives equal weight to every price in the window. It\'s smoother and slower than EMA, providing fewer false signals in trending markets but lagging more during trend changes. Common windows: 50 SMA (medium-term trend), 200 SMA (long-term trend). The 200 SMA is widely watched institutionally — being above or below it shapes how big traders allocate.',
    formula: 'SMA(N) = (Sum of last N closing prices) / N',
    example: '5-day SMA of closes [100, 102, 101, 103, 104] = (100+102+101+103+104) / 5 = 102. As the next bar closes, the oldest drops out and the newest enters, giving the next SMA value.',
    relatedTerms: ['ema', 'moving-average', 'bollinger-bands'],
    relatedPatterns: [],
  },
  {
    slug: 'fibonacci-retracement',
    term: 'Fibonacci Retracement',
    category: 'technical',
    shortDef: 'A tool drawing horizontal levels at 23.6%, 38.2%, 50%, 61.8%, and 78.6% of a prior move — common pullback zones.',
    fullDef: 'Fibonacci retracements are drawn from a swing low to a swing high (or vice versa) and identify common pullback levels. The 38.2% and 61.8% levels are most heavily watched. These are not magical numbers — they work because enough traders watch them to create self-fulfilling reaction zones. Confluence with horizontal support/resistance is what makes Fib levels powerful.',
    example: 'NIFTY rallied from 23500 to 24500 (1000-point move). The 50% retracement is 24000; 61.8% is 23882. A pullback to ~24000 that holds with bullish reversal candles often signals trend continuation.',
    relatedTerms: ['support', 'resistance', 'pivot-points'],
    relatedPatterns: [],
  },
  {
    slug: 'pivot-points',
    term: 'Pivot Points',
    category: 'technical',
    shortDef: 'Pre-calculated support and resistance levels for the current session, derived from prior session\'s high/low/close.',
    fullDef: 'Pivot points generate a daily reference set: a central pivot (P), three resistances (R1, R2, R3) above, and three supports (S1, S2, S3) below. Calculated from yesterday\'s high, low, and close, they\'re standardised across most platforms — meaning many traders watch the same lines, which gives them self-fulfilling power. Often used by intraday traders for entries, exits, and risk levels.',
    formula: 'P = (High + Low + Close) / 3;  R1 = 2P − Low;  S1 = 2P − High',
    example: 'Yesterday: high 24600, low 24300, close 24500. P = 24466. R1 = 2(24466) − 24300 = 24632. S1 = 2(24466) − 24600 = 24332. Today\'s session is likely to react at these levels.',
    relatedTerms: ['support', 'resistance', 'fibonacci-retracement'],
    relatedPatterns: [],
  },
  {
    slug: 'atr',
    term: 'ATR (Average True Range)',
    category: 'technical',
    shortDef: 'A volatility measure showing the typical range a price moves per period — useful for stop placement and sizing.',
    fullDef: 'ATR averages the "true range" (greatest of: today\'s high-low, today\'s high to yesterday\'s close, today\'s low to yesterday\'s close) over a lookback (typically 14). It tells you how much an asset usually moves per bar. Stops placed at less than 1×ATR are typically too tight; trailing stops at 2-3×ATR balance protection with breathing room. ATR-sized position sizing keeps risk constant across instruments of different volatility.',
    example: 'A stock trades at ₹500 with 14-day ATR of ₹8. A stop placed ₹3 away (less than 0.5×ATR) is likely to be hit by normal noise. A stop at ₹490 (1.25×ATR) is more reasonable.',
    relatedTerms: ['moving-average', 'bollinger-bands', 'trailing-stop', 'position-size'],
    relatedPatterns: [],
  },

  // ─────────────────────────────────────────────────────────────────
  // PSYCHOLOGY (5)
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'tilt',
    term: 'Tilt',
    category: 'psychology',
    shortDef: 'An emotionally compromised state where decisions are driven by frustration, anger, or panic rather than the trade plan.',
    fullDef: 'Borrowed from poker, "on tilt" describes the mental state that follows a bad beat or losing streak — the trader stops following their plan and starts making impulsive decisions. Symptoms: oversizing, taking marginal setups, ignoring stops, holding losers in hope of recovery. Tilt almost always leads to bigger losses; recognising it early and closing the platform is the only reliable fix.',
    example: 'After a -₹15,000 stop-out at 11 AM, the trader takes 8 more trades in the next hour without checking setup quality, ending the day -₹35,000. The morning loss became the entry point for tilt.',
    relatedTerms: ['drawdown-psychology', 'loss-aversion'],
    relatedPatterns: ['revenge-trade', 'panic-exit', 'overtrading', 'decision-fatigue'],
  },
  {
    slug: 'drawdown-psychology',
    term: 'Drawdown Psychology',
    category: 'psychology',
    shortDef: 'The mental challenges of experiencing a deep account decline — fear, doubt, and the urge to abandon the plan.',
    fullDef: 'Drawdowns test traders psychologically more than they do mathematically. A 25% drawdown is statistically routine for most strategies, but emotionally it feels catastrophic — leading to plan-abandonment ("this isn\'t working anymore"), oversizing ("I need to make it back"), and undertrading ("I\'m too scared to take setups"). The way out is mechanical adherence to the plan combined with reduced position size during the drawdown to protect mental capital.',
    example: 'A trader is 22% in drawdown. The strategy historically has 18% drawdowns. Statistically nothing is broken, but the trader stops taking valid setups (fear) and oversizes the ones they do take (recovery urge) — both make the drawdown deeper.',
    relatedTerms: ['drawdown', 'max-drawdown', 'loss-aversion'],
    relatedPatterns: ['revenge-trade', 'panic-exit', 'hope-and-hold'],
  },
  {
    slug: 'position-sizing-emotion',
    term: 'Position Sizing Emotion',
    category: 'psychology',
    shortDef: 'The tendency to size by feeling — bigger when confident, smaller when uncertain — rather than by rule.',
    fullDef: 'Position sizing is one of the most rule-amenable parts of trading, yet it\'s where emotion most aggressively overrides discipline. The "high conviction" trade gets 2-3x normal size; the "uncertain" setup gets half. The result is that emotional confidence drives risk-taking — and confidence has a poor correlation with trade outcomes. Mechanical sizing rules (% of equity, ATR-based) eliminate this leak.',
    example: 'A trader\'s normal size is 50 lots. After 3 wins they take 100 lots on the "obvious" 4th setup, which fails and erases the morning gains. Emotion-based sizing made the worst trade the largest.',
    relatedTerms: ['position-size', 'leverage'],
    relatedPatterns: ['overconfidence', 'larger-position', 'position-sizing-error'],
  },
  {
    slug: 'loss-aversion',
    term: 'Loss Aversion',
    category: 'psychology',
    shortDef: 'The well-documented tendency to feel losses about twice as strongly as equivalent gains.',
    fullDef: 'Loss aversion, formalised in prospect theory by Kahneman and Tversky, is a cognitive bias where the pain of a ₹1,000 loss exceeds the pleasure of a ₹1,000 gain by roughly 2:1. In trading, this drives premature profit-taking (locking small wins to feel good) and excessive loss-holding (deferring the realisation pain). The disposition effect is loss aversion in action.',
    example: 'A trader closes a +5% winner at the first wobble (locking the good feeling) but holds a -8% loser for weeks (deferring the bad feeling). Both decisions feel right in the moment but together create asymmetric R:R that destroys long-term P&L.',
    relatedTerms: ['prospect-theory', 'drawdown-psychology'],
    relatedPatterns: ['disposition-effect', 'premature-exit', 'hope-and-hold', 'sunk-cost-fallacy'],
  },
  {
    slug: 'prospect-theory',
    term: 'Prospect Theory',
    category: 'psychology',
    shortDef: 'A behavioural-economics framework explaining how people evaluate gains and losses asymmetrically under uncertainty.',
    fullDef: 'Developed by Kahneman and Tversky in 1979, prospect theory shows that people evaluate outcomes relative to a reference point (usually status quo) rather than in absolute terms, and that they\'re loss-averse by roughly 2:1. The theory explains many trading behaviours — risk-aversion in gains (premature exits), risk-seeking in losses (averaging down) — that classical finance can\'t. Awarded the 2002 Nobel Prize.',
    example: 'A trader given a coin flip for "₹5,000 win or ₹5,000 loss" usually declines (loss-aversion). The same trader, already down ₹5,000, will often take a coin flip for "double-or-nothing" because in losses, people become risk-seeking — the textbook prospect-theory result.',
    relatedTerms: ['loss-aversion', 'drawdown-psychology'],
    relatedPatterns: ['disposition-effect', 'averaging-down', 'hope-and-hold'],
  },

  // ─────────────────────────────────────────────────────────────────
  // RISK (6)
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'position-size',
    term: 'Position Size',
    category: 'risk',
    shortDef: 'The dollar (or rupee) amount allocated to a single trade — the most controllable variable in trading.',
    fullDef: 'Position size determines how much an outcome moves your account. The two common sizing methods are: (1) fixed-fractional, where each trade risks a fixed % of equity (e.g., 0.5%); (2) fixed-amount, where each trade has a fixed dollar size. Fixed-fractional is preferred for retail because it auto-adjusts as the account grows or shrinks. Position size has more impact on long-term returns than entry/exit timing.',
    formula: 'Position Size (shares) = (Account Equity × Risk %) / (Entry Price − Stop Price)',
    example: 'Account ₹5,00,000, risking 0.5% per trade = ₹2,500. Entry ₹500, stop ₹490 (₹10 risk per share). Position size = 2,500 / 10 = 250 shares.',
    relatedTerms: ['leverage', 'risk-reward-ratio', 'expectancy', 'atr'],
    relatedPatterns: ['position-sizing-error', 'larger-position', 'overconfidence'],
  },
  {
    slug: 'leverage',
    term: 'Leverage',
    category: 'risk',
    shortDef: 'Borrowed capital used to amplify position size — magnifies both gains and losses.',
    fullDef: 'Leverage is expressed as a multiplier (2x, 5x, 10x) or as a margin requirement (50% margin = 2x leverage). Higher leverage means smaller adverse moves cause larger percentage losses. A 5% adverse move on 10x leverage destroys 50% of margin. Retail crypto and forex products often offer 100x+ leverage; using anywhere near maximum almost guarantees liquidation. Most successful traders use 2-3x effective leverage at most.',
    example: 'Account ₹1,00,000 with 5x leverage → ₹5,00,000 position. A 2% move against the position = ₹10,000 loss = 10% of account equity. The same 2% move would be 2% loss with no leverage.',
    relatedTerms: ['position-size', 'margin', 'max-drawdown'],
    relatedPatterns: ['larger-position', 'panic-exit', 'position-sizing-error'],
  },
  {
    slug: 'margin',
    term: 'Margin',
    category: 'risk',
    shortDef: 'Collateral deposited with the broker to open and maintain a leveraged position.',
    fullDef: 'Margin comes in two flavours: initial margin (the upfront collateral required to open a position) and maintenance margin (the minimum equity that must be maintained while the position is open). Falling below maintenance margin triggers a margin call — the broker either demands more collateral or liquidates the position automatically, often at the worst possible price during a downward spiral.',
    example: 'Initial margin requirement is 50% on a ₹1,00,000 position → ₹50,000 of your money. Maintenance margin is 25%. If equity drops to ₹25,000 due to losses, you face a margin call. Failure to deposit more triggers forced liquidation.',
    relatedTerms: ['leverage', 'position-size'],
    relatedPatterns: ['panic-exit', 'larger-position'],
  },
  {
    slug: 'slippage',
    term: 'Slippage',
    category: 'risk',
    shortDef: 'The difference between the expected execution price and the actual fill price — a hidden trading cost.',
    fullDef: 'Slippage occurs when the market moves between order submission and execution, when liquidity is thin, or when an order is too large for the visible book. Market orders are most exposed; limit orders eliminate price slippage but trade off against execution risk. Slippage is highest in fast-moving instruments, low-liquidity hours, and around news events. Over many trades it compounds materially.',
    example: 'You place a market buy order when the ask is ₹500.50. By the time the order reaches the exchange, market orders ahead of you have lifted the ask to ₹500.80. Your fill is ₹500.80 — ₹0.30 of slippage per share.',
    relatedTerms: ['spread', 'commission', 'market-order', 'limit-order'],
    relatedPatterns: ['news-trading-fomo', 'chasing-momentum'],
  },
  {
    slug: 'spread',
    term: 'Spread',
    category: 'risk',
    shortDef: 'The difference between the best bid (buy) price and the best ask (sell) price — the immediate cost of round-tripping.',
    fullDef: 'The bid-ask spread is what market makers charge for providing liquidity. A tight spread (1-2 ticks) means you can enter and exit cheaply; a wide spread (10+ ticks) means you lose meaningful value just to enter. Spreads widen during news, low-liquidity hours, and in less-traded instruments. Always check spread before entering a position — over many trades, a 0.5% spread on round-trip is often larger than commissions.',
    example: 'Stock bid ₹499.50, ask ₹500.50. Spread = ₹1 (0.2% of price). To break even on a ₹500 buy, the price must rally to ₹500.50 just to recover the spread cost.',
    relatedTerms: ['slippage', 'commission', 'market-order', 'limit-order'],
    relatedPatterns: ['overtrading', 'news-trading-fomo'],
  },
  {
    slug: 'commission',
    term: 'Commission',
    category: 'risk',
    shortDef: 'The fee charged by the broker for executing a trade — a direct cost that compounds over high-frequency trading.',
    fullDef: 'Commissions vary widely: zero-commission US brokers (Robinhood) make money on payment-for-order-flow instead of charging direct fees; flat-fee Indian discount brokers charge ₹20 per executed F&O order regardless of size. For active traders, commissions can become a significant drag — 100 trades per month at ₹40 round-trip = ₹4,000/month, or ₹48,000/year. Always factor commissions into expectancy calculations.',
    example: 'Trading 5 round-trip F&O lots per day at ₹40 commission per round-trip = ₹200/day or roughly ₹50,000/year. A strategy with ₹1L/year gross profit is actually a ₹50K net strategy — change the assumption and the strategy may no longer be viable.',
    relatedTerms: ['slippage', 'spread'],
    relatedPatterns: ['overtrading'],
  },
]

/** Lookup a term by slug. Returns undefined when no match. */
export function getTerm(slug: string): GlossaryTerm | undefined {
  return GLOSSARY_TERMS.find((t) => t.slug === slug)
}

/** All slugs — convenient for static-site-generation `generateStaticParams`. */
export function getTermSlugs(): string[] {
  return GLOSSARY_TERMS.map((t) => t.slug)
}
